### ISSUE TITLE
APIs created via APIG's REST API are slower than apis created in AWS Web Console (not an issue with this importer)

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#41] opened 2015-09-21 19:52 UTC
Hi Ryan, 

I'm a big fan of your work here and I've created a javascript version for the [JAWS Framework](https://github.com/jaws-framework/JAWS) that is very similar to this.

I do not know if this issue affects your importer, but it affects mine.  Since the API Gateway REST API is your area of expertise, I'm hoping you can point out anything obvious that I am missing. 

In short, when people are creating APIG REST APIs with the JAWS command line tool, the response times are ~500ms slower than if the REST API is created in the AWS APIG UI.   This seems odd to me, since they both use the APIG REST API.  Perhaps there is are missing configuration settings that are resulting in poorer performance.  

[Further details on this issue can be found here](https://github.com/jaws-framework/JAWS/issues/139).  If  there is anything that comes to mind, please let me know.  If you're busy, I understand.  Please know your work is awesome and it helped me tremendously. 

Kindest regards,
Austen 
JAWS 

P.S.  Are you going to be @ Re:invent, and could I buy you a beer?

**Comment by rpgreen** [comment] 2015-09-21 20:46
Hey Austen,

There should be no difference in performance between an API created using the client vs the console. 

I just tried the 2 endpoints and got the same results from both. However, there's definitely a lot of variation in the latency and > 500ms is much higher than we would expect. Is the API under test making a cross region lambda call?

Have you been able to verify this yourself? Do you see the same pattern in other regions? 

Do the integrations created using JAWS specify a role ARN for credentials or are they using resource-based permissions (no role specified)? The console uses resource-based permissions which is the biggest potential difference I can think of.

Sadly I will be in Seattle holding down the fort during Re:invent :)

Cheers,
Ryan

**Comment by rpgreen** [comment] 2015-09-21 22:18
I've reproduced the issue. I believe this is related to specifying credentials to invoke the lambda function. You can get around this by leaving the integration credentials out of swagger/client, and making a call using the lambda cli/api to add a permission for API Gateway to call the lambda function. We're looking into it.

**Comment by austencollins** [comment] 2015-09-22 07:44
Ryan, 

You rock for figuring this out.  I'll implement the fix you suggested while you guys work on the core issue. 

It's a shame you aren't going to re:invent.  Seems odd since you're working on the "cool stuff".  The Lambda team has been super helpful with [JAWS](https://github.com/jaws-framework/JAWS).  Steffano also has chimed in with some helpful input.  But I'd still really enjoy a chat with you.  After all of the re:invent craziness is over, I'll drop an issue in here to see if you you're available.  Otherwise, you can reach me at austen [at] servant.co

Again, thanks for the great work Ryan :)

Take care,
Austen

**Comment by austencollins** [comment] 2015-09-23 19:21
Ryan, 

Shoot, another bug is blocking me from implementing your workaround.  [Details here](https://forums.aws.amazon.com/thread.jspa?threadID=216626&tstart=0).

Do you have any other suggestions?

Best regards,
Austen

**Comment by rpgreen** [comment] 2015-09-23 19:45
Answered in the forum. I don't think this is a bug, unless you can't stop the Node SDK from calling "get policy"

**Comment by austencollins** [comment] 2015-09-23 20:16
You are the man Ryan.  Seriously, thank you.  I have been pouring my life into this JAWS project and as a consequence I get overly worried about issues like these.  

Ok, so I can manually update the permissions now.  My only worry now is that JAWS has to programmatically manage people's Lambda access policies.  Using the credentials property is a lot cleaner.  Hopefully you guys can squash that latency soon.

Thanks again Ryan :)  You are doing really awesome work.  I wouldn't have made it this far without you.

Cheers,
Austen

**Comment by rpgreen** [comment] 2015-09-23 20:22
No problem. This is the way the API Gateway console works too. It's a better workflow since the user doesn't have to worry about managing another IAM role/policy. As long as the credentials used to make the call to Lambda are the users own credentials, it shouldn't be a concern.

**Comment by rpgreen** [comment] 2015-09-24 17:59
Hi Austen,

We have a solution for the latency issue which should be deployed early next week.

In order to take advantage of this, you'll need to instruct your users to opt-in for regionalized STS for the region where their API is located. It's quick step in the IAM web console.

Instructions are here: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

**Comment by austencollins** [comment] 2015-09-24 18:42
Ryan, 

Since you have domain expertise in this, I'm wondering if you could recommend a single implementation that would help JAWS accomplish the following goals:
- **User-friendliness:** JAWS is mostly a usability layer on top of the groundbreaking stuff you're making.
- **Best possible performance:**  What's going to offer the best response times for JAWS users?  Will STS be faster than specifying lambda permissions?
- **One size fits all:**  JAWS introduces the [aws-module (AWSM)](https://github.com/awsm-org/awsm) format for modularizing pre-written lambda code, but soon I also want to use aws-modules to modularize API Gateway configurations, which would include proxies to more resources than just lambda.  My feeling is that STS may be the silver bullet that will allow aws-modules to include all types of APIG configurations.  Is my thinking accurate?

I've already implemented the workaround you suggested to great success.  Response times are down by ~300ms.  But, I'm open to rewriting it if there is a better option.  Just not sure what that is at the moment.

Thanks, 
Austen

**Comment by rpgreen** [comment] 2015-09-24 19:10
For the first 2 points, when it comes to invoking lambda functions, resource-based permissions are definitely the way to go.

As you mentioned API Gateway can be used to proxy to most of the AWS services/operations and it would be awesome to have some canned configurations for popular use-cases. We have seen Kinesis and S3 come up a lot. Your thinking is accurate in that the key to handling all of these use-cases is the users IAM role with properly configured policy. STS is the mechanism we use internally to execute on behalf of the user. 

Can you point me to the code where you're adding the lambda permissions?

**Comment by austencollins** [comment] 2015-09-24 19:42
Ryan,

[Between lines 829 - 963](https://github.com/jaws-framework/JAWS/blob/master/lib/commands/deploy_endpoint.js#L829) is where the Lambda permissions are managed by JAWS.  The flow is like this when the endpoint is being deployed and the lambda permissions are being managed:
- Fetch the Lambda's Access Policy (AP)
- Check if there is a statement in the AP with a statement ID of 'jaws-apigateway-access'
- If statement exists, remove it
- Add new statement to Lambda's AP with ID 'jaws-apigateway-access'

Sounds like there isn't a one-size-fits-all implementation, and perhaps the way to go is to mix them?

**Comment by rpgreen** [comment] 2015-09-24 21:27
Looks great! Yeah I think you may want to go with a combination unless you're ok with the tradeoffs of using STS with lambda invocations

**Comment by austencollins** [comment] 2015-09-24 21:55
Ok thank you :)

Sorry to keep bugging you, but could you take a look at the statement I'm making to update Lambda's Access Policy.  I'm getting reports that people are getting this error: "Execution failed due to configuration error: Invalid permissions on Lambda function."

[The code that updates the policy is here](https://github.com/jaws-framework/JAWS/blob/master/lib/commands/deploy_endpoint.js#L926)

**Comment by rpgreen** [comment] 2015-09-24 22:22
The policy should look something like this:

```
...
"AWS:SourceArn":"arn:aws:execute-api:[REGION]:[ACCOUNT_ID]:[API_ID]/*/[HTTP_VERB]/[RESOURCE_PATH]"}},
"Action":"lambda:InvokeFunction",
"Resource":"arn:aws:lambda:[REGION]:[ACCOUNT_ID]:function:[FUNCTION_NAME]",
"Effect":"Allow",
"Principal":{"Service":"apigateway.amazonaws.com"}
...
```

**Comment by rpgreen** [comment] 2015-09-24 22:30
May be better to keep stage as a wildcard to keep the permissions stage-independent. Also test invokes from the console aren't tied to a stage.

**Comment by austencollins** [comment] 2015-09-30 01:48
Ryan, 

Thanks for your help.  Everything is working well now and fast :)

I just did an impromptu talk on JAWS @ the AWS Pop-up Loft in SF w/ Tim Wagner and Simon.  They said you were in town too.  Too bad we didn't get to meet! 

However, since you have been so awesome helping me out, I had already included your name in my JAWS slides a few days ago, in the "Special Thanks" section, which prompted a brief chat about you.  Then I went and hyped you up further to Simon because you are that awesome.  

Hopefully there is a raise coming your way soon :+1: 

Best, 
Austen

**Comment by rpgreen** [comment] 2015-09-30 18:44
Awesome - I would have made an effort to get up there had I known! I heard the JAWS presentation went really well. Thanks for the shout out, always helps :)

**Comment by rpgreen** [comment] 2015-10-19 16:27
Closing this issue - please reopen if there's anything outstanding

**Closed as completed by rpgreen** 2015-10-19 16:27 UTC

**Comment by austencollins** [comment] 2015-12-22 16:13
Hi Ryan, 

Just checking in on this issue.  Have you guys been able to remove the extra latency when specifying credentials, or should we continue adding the policy to the Lambda function?

I hope you are well.  Happy holidays too!

Austen

**Comment by rpgreen** [comment] 2015-12-22 17:18
Hi Austen,

Happy holidays to you as well!

It will be impossible to remove all the latency when using STS credentials - however, if [regional endpoints](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) are enabled for STS, the latency difference should be very small. We have also implemented credential caching which will greatly improve performance for APIs receiving steady traffic. I wouldn't expect any significant average latency difference between role-based and resource-based at this point but I would encourage you to do some benchmarking. If you notice any big differences please let us know.

We are also looking into automating the addition of resource-based permissions to make setting up APIs with lambda functions/resource-based permissions easier.

Cheers,
Ryan

**Comment by austencollins** [comment] 2015-12-22 21:40
Ryan, 

All of this sounds great.  Thank you for your hard work, as always.

Cheers,
Austen
