### ISSUE TITLE
Simple Hello World API Import examples

### ISSUE THREAD

**Issue by lashex** [awslabs/aws-apigateway-swagger-importer#61] opened 2015-10-21 17:26 UTC
Instead of the generic command examples

```
./aws-api-import.sh --create path/to/swagger.json
./aws-api-import.sh -c path/to/api.raml
```

which really only show me how to use a CLI. It would be nice to have a `hello.swagger` and a `hello.raml` file which are in the repo and used in delineated examples in the README documentation. This would help people who are familiar with API Gateway, but not as familiar with Swagger nor this importer.

_Example_

```
./aws-api-import.sh -t hello.swagger
...and expected output...
./aws-api-import.sh -c hello.swagger
...and expected output...
./aws-api-import.sh -t hello.raml
...and expected output...
./aws-api-import.sh -c hello.raml
...and expected output...
```

**Comment by rpgreen** [comment] 2015-10-21 22:12
Duplicate of #30

**Closed as completed by rpgreen** 2015-10-21 22:12 UTC
