### ISSUE TITLE
API cannot be tested from console after import

### ISSUE THREAD

**Issue by ifullgaz** [awslabs/aws-apigateway-swagger-importer#136] opened 2015-12-30 00:15 UTC
After importing a simple API (file enclosed), I'm trying to test the methods by using the Test button in the console.
However, I get an Internal Server Error with that line in the log:

```
Execution failed due to configuration error: Invalid permissions on Lambda function
```

My lambda functions all have the following role attached to them:
Permission policy: AWSLambdaExecute

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:*"
      ],
      "Resource": "arn:aws:logs:*:*:*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Resource": "arn:aws:s3:::*"
    }
  ]
}
```

Trusted Entities policies:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

When I reselect the same lambda function in the console, a message warns me that API Gateway will be given permission to run the function. After this, I can use the Test button in the console.
Could you make this process automatic as well?
Thanks

[TestImporter.zip](https://github.com/awslabs/aws-apigateway-importer/files/74496/TestImporter.zip)

**Comment by kahouieong** [comment] 2015-12-30 00:25
@ifullgaz 
We will prioritize to add the similar feature to the importer. Thank you for your feedback.

**Comment by ifullgaz** [comment] 2015-12-30 00:28
Thanks!

**Comment by rpgreen** [comment] 2015-12-30 18:35
Dupe of https://github.com/awslabs/aws-apigateway-importer/issues/111

**Closed as completed by rpgreen** 2015-12-30 18:35 UTC
